version: '3.8'
services:
  react-ts-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
    command: npm start
    stdin_open: true
    restart: always
    container_name: react-ts-container